### PR TITLE
Upgrade Angular to 13.0.0

### PR DESCRIPTION
**Pull request by cheng-atf**
Hello,

this PR is only about upgrading angular and typescript versions. 

- Angular from 8.2.5 to 13.0.0
- Typescript from 3.5.3 to 4.3.2

Note that there's newer versions of typescript, but I deliberately set it to 4.3.2 to make it work with Yarn.

### CODE REVIEW

**Comment by Kuinox** [comment]
Hello,
are you sure about Angular 13 ? AFAIK all our project cannot run on 13 because ng-zorro is still on 12.

For the typescript downgrade: upgrade yarn first, it should work with the lastest typescript, yarn is installed in the repo.

**Comment by cheng-atf** [comment]
> Hello, are you sure about Angular 13 ? AFAIK all our project cannot run on 13 because ng-zorro is still on 12.
> 
> For the typescript downgrade: upgrade yarn first, it should work with the lastest typescript, yarn is installed in the repo.

Indeed, we could release a version using Angular 12 for now, I agree.

Regarding yarn, I'm currently using yarn v2.4.2, and having issues upgrading typescript to 4.4.4.

**Comment by Kuinox** [comment]
There is a 2.4.3 version available and a 3.1.0 too, i'm checking the breaking change to see if we can update without issues.

**Comment by Kuinox** [comment]
Looks like there is some files changes, I would recommend to remove all yarn related files except package.json then install a fresh yarn 3.  
To be sure: what was your issue with typescrit 4 and yarn ?

**Comment by Kuinox** [comment]
> ➤ YN0000: Failed with errors in 36m 23s

Holy shit, it took 36 minutes to run a yarn install????
image
wtf

**Comment by Kuinox** [comment]
@Drazny if you do a yarn install it will update the package lockfile, and it will solve the deadlock issue.

**Pull request closed without merging**
